inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1.1
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
  NewCops: enable

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout:
  Enabled: true

Lint:
  Enabled: true

Security:
  Enabled: true

Style:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true

Style/RequireOrder:
  Enabled: true
  SafeAutoCorrect: true

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/RedundantReturn:
  Enabled: false
