require:
  - rubocop/cop/internal_affairs
  - rubocop-rake
  - rubocop-rspec
  - ./lib/momocop

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1.1
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout:
  Enabled: true

Lint:
  Enabled: true

Security:
  Enabled: true

Style:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  SafeAutoCorrect: true

Style/IfUnlessModifier:
  Enabled: false

Style/RequireOrder:
  Enabled: true
  SafeAutoCorrect: true

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/RedundantReturn:
  Enabled: false
