Momocop/RSpecDescribeTextPattern:
  Description: 'Ensures that RSpec describe text matches the configured pattern'
  Enabled: true
  RequiredPattern: '^(?!When ).+'

Momocop/RSpecContextTextPattern:
  Description: 'Ensures that RSpec context text starts with When or If'
  Enabled: true
  RequiredPattern: '^(When|If) .+'
