name: Spec

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '4.0'
          - '3.3'
          - '3.2'
          - '3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec

  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Run 'readme:update' task
      run: bundle exec rake readme:update
    - name: Show git diff
      run: git diff
    - name: Show git status
      run: git status --porcelain
    - name: Check for uncommitted changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Uncommitted changes detected. Did you forget to update README.md or README.ja.md?"
          exit 1
        fi
